### ISSUE TITLE
if size of the last packet is smaller than 128, it still send STX

### ISSUE THREAD

**Issue by Sieyalixnet** [TGMM/xymodem.rs#2]
It should send 128 packet with SOH header according to YMODEM in wikipedia
[When such a connection was started, the sender could choose to send either 1024 bytes in a packet or 128, indicating the larger with an STX character in the header rather than the normal SOH.](https://en.wikipedia.org/wiki/YMODEM#1k)

But the `send_stream` function DOES NOT change the header according to the size of the packet:

```rust
    fn send_stream<D: Read + Write, R: Read>(
        &mut self,
        dev: &mut D,
        stream: &mut R,
        packets_to_send: u32,
        last_packet_size: u64,
    ) -> Result<()> {
        let mut block_num = 0u32;
        loop {
            let packet_size = if block_num + 1 == packets_to_send && last_packet_size <= 128 {
                128
            } else {
                1024
            };
.....
            block_num += 1;
            buff[0] = STX;
            buff[1] = (block_num & 0xFF) as u8;
            buff[2] = 0xFF - buff[1];
```

it should be 

```rust
    fn send_stream<D: Read + Write, R: Read>(
        &mut self,
        dev: &mut D,
        stream: &mut R,
        packets_to_send: u32,
        last_packet_size: u64,
    ) -> Result<()> {
        let mut block_num = 0u32;
        loop {
            let packet_size = if block_num + 1 == packets_to_send && last_packet_size <= 128 {
                128
            } else {
                1024
            };
......
            if packet_size == 128 {
                buff[0] = SOH;
            } else {
                buff[0] = STX;
            }
```

**Comment by TGMM** [comment]
Thanks a lot for pointing that out! As you have probably realized, I don't really maintain this crate anymore. I'm planning to create a new one that has cross-compatibility with WASM so it works for both Rust and JS while also being async, but haven't had time as of yet. 

With that out of the way I have noticed some people do use this package (which is awesome!) and I think your change could probably help those who want a solution right now. If it's possible, could you open a PR with this change so I can merge it?

**Comment by Sieyalixnet** [comment]
> Thanks a lot for pointing that out! As you have probably realized, I don't really maintain this crate anymore. I'm planning to create a new one that has cross-compatibility with WASM so it works for both Rust and JS while also being async, but haven't had time as of yet.
> 
> With that out of the way I have noticed some people do use this package (which is awesome!) and I think your change could probably help those who want a solution right now. If it's possible, could you open a PR with this change so I can merge it?

Thanks your reply. I created a PR.
